services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
    networks:
      - app

  database:
    container_name: database
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      - app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 3s
      retries: 20

  backend:
    container_name: backend
    restart: always
    build:
      context: ./
    volumes:
      - .:/app
      - /app/vendor
    ports:
      - "8000:8000"
    networks:
      - app
    depends_on:
      database:
        condition: service_healthy

networks:
  app:
    driver: bridge
